"""new fields in user model

Revision ID: 77446a4590ee
Revises: 97f9dad610aa
Create Date: 2022-04-23 16:12:47.967442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77446a4590ee'
down_revision = '97f9dad610aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
